#!/usr/bin/env python3
"""
generate_charter.py — Generate a project charter Markdown draft.

Usage:
    python generate_charter.py \
        --project-name "EdgeFlow Platform" \
        --company-a "Acme Corp" \
        --company-b "BuildCo" \
        --goals "Ingest 50k events/sec,Enable real-time alerting,Deliver in 6 months" \
        --output charter-draft.md

The script produces a populated Markdown charter draft based on the inputs provided.
Edit the output to fill in stakeholder names, specific dates, and detailed SLAs.
"""

import argparse
import sys
from datetime import date, timedelta


def build_charter(project_name: str, company_a: str, company_b: str, goals: list[str]) -> str:
    today = date.today()
    m0 = today
    m1 = today + timedelta(weeks=4)
    m2 = today + timedelta(weeks=12)
    m3 = today + timedelta(weeks=18)
    m4 = today + timedelta(weeks=20)

    goals_list = "\n".join(f"{i+1}. {g.strip()}" for i, g in enumerate(goals))

    charter = f"""# Project charter: {project_name}

**Version:** 1.0
**Date:** {today.isoformat()}
**Status:** Draft — pending review and sign-off

---

## 1. Executive summary

**Project name:** {project_name}
**Companies:** {company_a} (Company A) and {company_b} (Company B)

[Add a one-paragraph description of the project here. Describe what is being built,
which company is responsible for which parts, and what the expected outcome is.]

---

## 2. Project purpose and business objectives

**Problem statement:**
[Describe the business problem this project solves.]

**Business objectives:**
{goals_list}

**Strategic alignment:**
- **{company_a}:** [How this project aligns with Company A's strategy]
- **{company_b}:** [How this project aligns with Company B's strategy]

---

## 3. Scope

### In scope

| # | Deliverable | Owner | Milestone |
|---|-------------|-------|-----------|
| 1 | [Deliverable 1] | {company_b} | M1 |
| 2 | [Deliverable 2] | {company_b} | M2 |
| 3 | [Deliverable 3] | Shared | M3 |
| 4 | [Specification and review] | {company_a} | M1 |

### Out of scope (explicit)

The following are explicitly NOT in scope:
- [Item 1 — be specific]
- [Item 2 — be specific]
- [Item 3 — be specific]

---

## 4. Success metrics and exit criteria

The project is complete when ALL of the following criteria are met:

| Criterion | Measurement method | Target |
|-----------|-------------------|--------|
| All acceptance tests pass | Automated test suite | 100% pass rate |
| Security gates passed | Security review sign-off | All Critical/High resolved |
| Performance SLOs met | Load test results | [Define targets] |
| Documentation complete | Documentation checklist | All items checked |

---

## 5. Key stakeholders

| Name | Company | Role | Contact |
|------|---------|------|---------|
| [TBD] | {company_a} | VP Engineering | [email] |
| [TBD] | {company_a} | Lead Architect | [email] |
| [TBD] | {company_b} | Engineering Manager | [email] |
| [TBD] | {company_b} | Tech Lead | [email] |

---

## 6. SLA commitments

### Service level objectives (production)

| Metric | Target | Window |
|--------|--------|--------|
| API availability | 99.9% | 30 days rolling |
| p99 latency | [Define] | 7 days rolling |

### Partner delivery SLAs

| Commitment | SLA |
|------------|-----|
| Response to architecture review comments | 2 business days |
| Critical defect resolution | 24 hours |
| High defect resolution | 5 business days |

---

## 7. Timeline and milestones

| Milestone | Description | Target date | Owner |
|-----------|-------------|-------------|-------|
| M0 — Kickoff | Charter signed, environments provisioned | {m0.isoformat()} | Both |
| M1 — Contracts frozen | API specs approved and frozen | {m1.isoformat()} | {company_a} |
| M2 — Core delivery | Core implementation complete | {m2.isoformat()} | {company_b} |
| M3 — Release ready | Load tested, security reviewed, docs complete | {m3.isoformat()} | Both |
| M4 — Production | Live in production | {m4.isoformat()} | Both |

Note: These are indicative dates based on a {(m4 - m0).days // 7}-week engagement.
Adjust to match actual sprint planning.

---

## 8. Governance structure

**Scope change authority:**
- Minor changes (≤3 days): Engineering Manager ({company_b}) + Lead Architect ({company_a})
- Major changes (>3 days): VP Engineering approval required (both companies)

**Escalation path:**
1. Engineering leads → same-day resolution expected
2. Engineering Managers → 48-hour resolution expected
3. VP Engineering → 5-business-day resolution expected

---

## 9. Sign-off

| Name | Company | Role | Signature | Date |
|------|---------|------|-----------|------|
| | {company_a} | VP Engineering | | |
| | {company_b} | Engineering Manager | | |

---

*Generated by generate_charter.py on {today.isoformat()}*
*Review and customise all sections marked with [brackets] before presenting for sign-off.*
"""
    return charter


def main():
    parser = argparse.ArgumentParser(
        description="Generate a project charter Markdown draft.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument("--project-name", required=True, help="Name of the project")
    parser.add_argument("--company-a", required=True, help="Name of Company A (the reviewing/governing company)")
    parser.add_argument("--company-b", required=True, help="Name of Company B (the implementing/partner company)")
    parser.add_argument("--goals", required=True, help="Comma-separated list of business goals")
    parser.add_argument("--output", default=None, help="Output file path (default: print to stdout)")

    args = parser.parse_args()

    goals = [g.strip() for g in args.goals.split(",") if g.strip()]
    if not goals:
        print("Error: at least one goal is required.", file=sys.stderr)
        sys.exit(1)

    charter = build_charter(args.project_name, args.company_a, args.company_b, goals)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(charter)
        print(f"Charter draft written to: {args.output}")
    else:
        print(charter)


if __name__ == "__main__":
    main()
